spring.application.name=ecommerce

# BANCO DE DADOS H2
#spring.h2.console.enabled=true
#spring.datasource.url=jdbc:h2:mem:test

#BANCO DE DADOS MYSQL
#spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce
#spring.datasource.username=root
#spring.datasource.password=${DB_PASSWORD:senha-padrao-dev}

#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

#BANCO DE DADOS POSTGRESQL
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/ecommerce}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:senha-padrao-dev}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

aplicacao.caminho.imagens=imagens/

#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true

aplicacao.jwt.segredo=${JWT_SECRET:chave-padrao-apenas-para-desenvolvimento-local}
aplicacao.jwt.expiracao-ms=3000000
aplicacao.jwt.nome-cookie=springBootEcom

#logging.level.org.springframework=DEBUG
#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.springframework.security=DEBUG
#logging.level.com.joaoneto.ecommerce=DEBUG

server.port=${PORT:8080}

imagem.base.url=${IMAGEM_BASE_URL:http://localhost:8080/imagens}

cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}

aplicacao.cors.origens-permitidas=${FRONTEND_URLS:http://localhost:5173,http://localhost:5174}

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

