spring.application.name=ecommerce

spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:test

aplicacao.caminho.imagens=imagens/

aplicacao.jwt.segredo=${JWT_SECRET:chave-padrao-apenas-para-desenvolvimento-local}
aplicacao.jwt.expiracao-ms=3000000
aplicacao.jwt.nome-cookie=springBootEcom

logging.level.org.springframework=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.com.joaoneto.ecommerce=DEBUG